### ISSUE TITLE
make a error popup

### ISSUE THREAD

**Issue by asylumexp** [srcoggin/FIA2#1]
https://github.com/srcoggin/FIA2/blob/276ea7bee2d5f9860f745677a8207bcb9f7ac98c/ui_new.py#L115

**Comment by srcoggin** [comment]
Shut the hell up bro

From: Sam Heinz ***@***.***>
Sent: Wednesday, May 24, 2023 6:58 PM
To: srcoggin/FIA2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [srcoggin/FIA2] make a error popup (Issue #1)


https://github.com/srcoggin/FIA2/blob/276ea7bee2d5f9860f745677a8207bcb9f7ac98c/ui_new.py#L115<https://github.com/srcoggin/FIA2/blob/276ea7bee2d5f9860f745677a8207bcb9f7ac98c/ui_new.py#L115>

**Comment by srcoggin** [comment]
This is now done
